version: "2.3"
services: 
    kaggle:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: kaggle:latest
        container_name: kaggle
        runtime: nvidia
        environment: 
            - NVIDIA_VISIBLE_DEVICES=all
        volumes: 
            - .:/workspace
        ports: 
            - "20021:20022"
        working_dir: /workspace
