version: "2.3"
services: 
    mycuda:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: mycuda:latest
        container_name: mycuda
        runtime: nvidia
        environment: 
            - NVIDIA_VISIBLE_DEVICES=all
        volumes: 
            - .:/workspace
        working_dir: /workspace
